export const destinations = [
	{
		title: 'Destino 1',
		restrictions: 'el minimo es de 1 pasajero',
		date: 'Nov 12',
		description: 'Texto explicando ventajas 1',
		image: 'https://source.unsplash.com/random',
		imageLabel: 'Image Text',
		price: 155,
		rating: 1,
	},
	{
		title: 'Destino 2',
		restrictions: 'el minimo es de 1 pasajero',
		date: 'Nov 11',
		description: 'Texto explicando ventajas 2',
		image: 'https://source.unsplash.com/random',
		imageLabel: 'Image Text',
		rating: 2,
		price: 155,
	},
	{
		title: 'Destino 3',
		restrictions: 'el minimo es de 1 pasajero',
		date: 'Nov 11',
		description: 'Texto explicando ventajas 3',
		image: 'https://source.unsplash.com/random',
		imageLabel: 'Image Text',
		rating: 3,
		price: 155,
	},
	{
		title: 'Destino 4',
		restrictions: 'el minimo es de 1 pasajero',
		date: 'Nov 11',
		description: 'Texto explicando ventajas 4	',
		image: 'https://source.unsplash.com/random',
		imageLabel: 'Image Text',
		rating: 4,
		price: 155,
	},
	{
		title: 'Destino 5',
		restrictions: 'el minimo es de 1 pasajero',
		date: 'Nov 12',
		description: 'Texto explicando ventajas 1',
		image: 'https://source.unsplash.com/random',
		imageLabel: 'Image Text',
		price: 155,
		rating: 5,
	},
	{
		title: 'Destino 6',
		restrictions: 'el minimo es de 1 pasajero',
		date: 'Nov 12',
		description: 'Texto explicando ventajas 1',
		image: 'https://source.unsplash.com/random',
		imageLabel: 'Image Text',
		price: 155,
		rating: 6,
	},
	{
		title: 'Destino 7',
		restrictions: 'el minimo es de 1 pasajero',
		date: 'Nov 12',
		description: 'Texto explicando ventajas 1',
		image: 'https://source.unsplash.com/random',
		imageLabel: 'Image Text',
		price: 155,
		rating: 7,
	},
	{
		title: 'Destino 8',
		restrictions: 'el minimo es de 1 pasajero',
		date: 'Nov 12',
		description: 'Texto explicando ventajas 1',
		image: 'https://source.unsplash.com/random',
		imageLabel: 'Image Text',
		price: 155,
		rating: 8,
	},
	{
		title: 'Destino 9',
		restrictions: 'el minimo es de 1 pasajero',
		date: 'Nov 12',
		description: 'Texto explicando ventajas 1',
		image: 'https://source.unsplash.com/random',
		imageLabel: 'Image Text',
		price: 155,
		rating: 9,
	},
];
